dist: focal

language: cpp
compiler: gcc

notifications:
  email: false

addons:
  apt:
    packages:
      - cmake
      - ninja-build
      - build-essential

before_script:
  - export CC=/usr/bin/gcc-9
  - export CXX=/usr/bin/g++-9

  - g++ --version
  - cmake --version

script:
  - mkdir build
  - cd build

  - cmake .. -DCMAKE_BUILD_TYPE=Debug -GNinja
  - ninja

  - cd test
  - ./abby-test